## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
GHCOPTS    = --make

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Interpreter

Interpreter : Main.hs
	ghc --make Main.hs -o Interpreter

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o Interpreter

# EOF
